import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { motion, AnimatePresence } from "framer-motion";
import {
  ArrowRight,
  ArrowLeft,
  Check,
  Pencil,
  Sparkles,
  Building2,
  Megaphone,
  ListChecks,
  ScrollText,
  FileText,
  Package,
  Gift,
  Users,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import {
  PIKORA_PRODUCTS,
  type PikoraProduct,
  PIKORA_BRAND_DESCRIPTION,
  PIKORA_TERMS,
  PIKORA_GIFTING_INSTRUCTIONS,
} from "@/data/pikora-mock-data";

// ─── Step definitions ────────────────────────────────────────────────────────

interface Step {
  title: string;
  subtitle: string;
  key: string;
  type: "textarea" | "products" | "creators" | "review";
  icon: typeof Building2;
  examples?: string[];
  examplesLabel?: string;
  autoGenerated?: boolean;
}

const STEPS: Step[] = [
  {
    title: "About Your Brand",
    subtitle: "Tell creators who you are. Drafted from your profile — edit freely.",
    key: "brandDescription",
    type: "textarea",
    icon: Building2,
    examplesLabel: "Tips",
    examples: [
      "Lead with what makes you different",
      "Keep it to 2–3 sentences — punchy beats long",
      "Mention key claims creators can talk about",
    ],
    autoGenerated: true,
  },
  {
    title: "About This Campaign",
    subtitle: "Describe the vibe, theme, or story you want creators to tell.",
    key: "campaignDescription",
    type: "textarea",
    icon: Megaphone,
    examples: [
      "Show your morning routine with Pikora as the warm-up ritual",
      "Taste-test all 3 Pikora flavors and rank your favorite",
      "Show how you swap your usual coffee or snack for Pikora bone broth",
    ],
  },
  {
    title: "Content Deliverables",
    subtitle: "What should creators post? One deliverable per line.",
    key: "deliverables",
    type: "textarea",
    icon: ListChecks,
    examples: [
      "1 TikTok video (30–60s) preparing and tasting Pikora",
      "1 Instagram Reel featuring Pikora in a daily routine",
      "3 Instagram Stories: unboxing, preparing, and final sip reaction",
    ],
    autoGenerated: true,
  },
  {
    title: "Other Requirements",
    subtitle: "Hashtags, tags, timelines — anything else creators need to know.",
    key: "otherRequirements",
    type: "textarea",
    icon: ScrollText,
    examples: [
      "Use #PIKORA and #BoneBrothButPowdered",
      "Tag @drinkpikora in all posts",
      "Show the stir/mix moment when preparing the broth",
    ],
    autoGenerated: true,
  },
  {
    title: "Terms & Commitments",
    subtitle: "Creators see this before accepting. Edit to fit your needs.",
    key: "terms",
    type: "textarea",
    icon: FileText,
    examples: [
      "Post content within 14 days of receiving your Pikora pack",
      "Brand retains usage rights for 12 months across social channels",
      "Include #ad or #gifted disclosure per FTC guidelines",
    ],
    autoGenerated: true,
  },
  {
    title: "Select Products",
    subtitle: "Pick the products creators will feature, then set conditions.",
    key: "products",
    type: "products",
    icon: Package,
    examples: [
      "Feature your top 2–3 Pikora flavors for variety content",
      "Let creators pick their favorite: Cocoa, Chicken, or Veggie",
      "Include the variety pack so creators can compare all flavors",
    ],
  },
  {
    title: "Gifting Instructions",
    subtitle: "How do creators choose and receive their product?",
    key: "giftingInstructions",
    type: "textarea",
    icon: Gift,
    examples: [
      "Creator picks 1 Pikora flavor, we ship a 12-pack within 3 days",
      "Include a tasting card with suggested recipes in the package",
      "Add a personal note thanking them for joining the Pikora family",
    ],
    autoGenerated: true,
  },
  {
    title: "Ideal Creator",
    subtitle: "Who should apply? Describe your perfect match.",
    key: "creators",
    type: "creators",
    icon: Users,
    examples: [
      "Wellness, food, or fitness creators who cook at home",
      "1K–50K followers, US-based, women & men 22–40",
      "Authentic taste-test, recipe, or morning routine content style",
    ],
  },
  {
    title: "Review & Launch",
    subtitle: "Double-check everything, then go live.",
    key: "review",
    type: "review",
    icon: Sparkles,
  },
];

// ─── Animation variants ──────────────────────────────────────────────────────

const variants = {
  enter: (dir: number) => ({ y: dir > 0 ? 30 : -30, opacity: 0 }),
  center: { y: 0, opacity: 1 },
  exit: (dir: number) => ({ y: dir > 0 ? -30 : 30, opacity: 0 }),
};

const transition = {
  duration: 0.3,
  ease: [0.22, 1, 0.36, 1] as [number, number, number, number],
};

// ─── Form state type ─────────────────────────────────────────────────────────

interface FormState {
  brandDescription: string;
  campaignDescription: string;
  deliverables: string;
  otherRequirements: string;
  terms: string;
  selectedProductIds: Set<string>;
  productConditions: string;
  giftingInstructions: string;
  creatorNiche: string;
  creatorFollowerRange: string;
  creatorGeography: string;
  creatorDemographics: string;
  creatorPlatforms: string;
  creatorStyle: string;
}

// ─── Shared styles ───────────────────────────────────────────────────────────

const textareaStyle =
  "w-full min-h-[140px] text-[15px] leading-relaxed rounded-xl border border-[var(--neutral-200)] bg-white px-4 py-3 resize-none outline-none focus:border-[var(--brand-600)] focus:ring-2 focus:ring-[var(--brand-600)]/10 text-[var(--neutral-800)] placeholder:text-[var(--neutral-300)] transition-all";

const inputStyle =
  "w-full text-[15px] rounded-xl border border-[var(--neutral-200)] bg-white px-4 py-2.5 outline-none focus:border-[var(--brand-600)] focus:ring-2 focus:ring-[var(--brand-600)]/10 text-[var(--neutral-800)] placeholder:text-[var(--neutral-300)] transition-all";

// ─── Component ───────────────────────────────────────────────────────────────

export default function CreateCampaignV2a() {
  const navigate = useNavigate();
  const [step, setStep] = useState(0);
  const [direction, setDirection] = useState<1 | -1>(1);

  const [form, setForm] = useState<FormState>({
    brandDescription: PIKORA_BRAND_DESCRIPTION,
    campaignDescription: "",
    deliverables:
      "Create 1 TikTok video (30\u201360 seconds) showing you preparing and tasting PIKORA\nCreate 1 Instagram Reel featuring PIKORA in your daily routine",
    otherRequirements:
      "Use campaign hashtag #PIKORA #BoneBrothButPowdered\nTag @drinkpikora in all posts\nShow the product being prepared (stir/mix moment)",
    terms: PIKORA_TERMS,
    selectedProductIds: new Set<string>(),
    productConditions: "",
    giftingInstructions: PIKORA_GIFTING_INSTRUCTIONS,
    creatorNiche: "",
    creatorFollowerRange: "",
    creatorGeography: "",
    creatorDemographics: "",
    creatorPlatforms: "",
    creatorStyle: "",
  });

  const currentStep = STEPS[step];
  const StepIcon = currentStep.icon;

  function updateField(key: string, value: string) {
    setForm((prev) => ({ ...prev, [key]: value }));
  }

  function toggleProduct(productId: string) {
    setForm((prev) => {
      const next = new Set(prev.selectedProductIds);
      if (next.has(productId)) next.delete(productId);
      else next.add(productId);
      return { ...prev, selectedProductIds: next };
    });
  }

  function handleNext() {
    if (step === STEPS.length - 1) {
      navigate("/campaigns");
      return;
    }
    setDirection(1);
    setStep((s) => Math.min(s + 1, STEPS.length - 1));
  }

  function handleBack() {
    setDirection(-1);
    setStep((s) => Math.max(s - 1, 0));
  }

  function goToStep(target: number) {
    setDirection(target > step ? 1 : -1);
    setStep(target);
  }

  function getFieldValue(key: string): string {
    return (form as unknown as Record<string, unknown>)[key] as string ?? "";
  }

  // ── Step renderers ──────────────────────────────────────────────────────

  function renderTextareaStep() {
    return (
      <div className="space-y-4">
        {currentStep.autoGenerated && (
          <div className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-[var(--brand-50)] text-[var(--brand-700)] text-[12px] font-medium">
            <Sparkles className="size-3" />
            Auto-generated from your profile
          </div>
        )}
        <textarea
          autoFocus
          className={textareaStyle}
          value={getFieldValue(currentStep.key)}
          onChange={(e) => updateField(currentStep.key, e.target.value)}
          onKeyDown={(e) => {
            if (e.key === "Enter" && !e.shiftKey) {
              e.preventDefault();
              handleNext();
            }
          }}
          placeholder="Type your answer here..."
        />
        <p className="text-[11px] text-[var(--neutral-300)] -mt-2">
          Shift + Enter for new line · Enter to continue
        </p>
      </div>
    );
  }

  function renderProductsStep() {
    const selectedCount = form.selectedProductIds.size;

    return (
      <div className="space-y-5">
        <div className="grid grid-cols-2 gap-3">
          {PIKORA_PRODUCTS.map((product: PikoraProduct) => {
            const selected = form.selectedProductIds.has(product.id);
            return (
              <button
                key={product.id}
                type="button"
                onClick={() => toggleProduct(product.id)}
                className="relative rounded-xl border p-3.5 text-left transition-all"
                style={{
                  borderColor: selected
                    ? "var(--brand-600)"
                    : "var(--neutral-200)",
                  backgroundColor: selected ? "var(--brand-50)" : "white",
                }}
              >
                <img
                  src={product.image}
                  alt={product.title}
                  className="w-14 h-14 rounded-lg object-cover mb-2.5"
                />
                <p className="font-semibold text-sm text-[var(--neutral-800)] leading-tight">
                  {product.title}
                </p>
                <p className="text-xs text-[var(--neutral-500)] mt-0.5">
                  {product.variant}
                </p>
                <p className="text-sm font-bold text-[var(--brand-700)] mt-1.5">
                  {product.price}
                </p>
                {selected && (
                  <div className="absolute top-3 right-3 flex items-center justify-center w-5 h-5 rounded-full bg-[var(--brand-700)]">
                    <Check className="size-3 text-white" strokeWidth={3} />
                  </div>
                )}
              </button>
            );
          })}
        </div>

        {selectedCount > 0 && (
          <div className="space-y-2 pt-2 border-t border-[var(--neutral-100)]">
            <div className="flex items-center justify-between">
              <label className="text-xs font-medium text-[var(--neutral-600)] uppercase tracking-wider">
                Conditions
              </label>
              <span className="text-xs text-[var(--brand-700)] font-medium">
                {selectedCount} selected
              </span>
            </div>
            <textarea
              className={textareaStyle + " !min-h-[80px]"}
              value={form.productConditions}
              onChange={(e) =>
                updateField("productConditions", e.target.value)
              }
              placeholder='How should creators choose? e.g., "Pick 1 flavor"'
            />
          </div>
        )}
      </div>
    );
  }

  function renderCreatorsStep() {
    const fields = [
      { label: "Niche", key: "creatorNiche", placeholder: "e.g., Wellness, Food, Fitness" },
      { label: "Follower Range", key: "creatorFollowerRange", placeholder: "e.g., 1K\u201350K" },
      { label: "Geography", key: "creatorGeography", placeholder: "e.g., US-based" },
      { label: "Demographics", key: "creatorDemographics", placeholder: "e.g., Women & men 22\u201340" },
      { label: "Platforms", key: "creatorPlatforms", placeholder: "e.g., TikTok, Instagram" },
      { label: "Content Style", key: "creatorStyle", placeholder: "e.g., Authentic lifestyle, recipe demos...", type: "textarea" as const },
    ];

    return (
      <div className="space-y-4">
        {fields.map((field) => (
          <div key={field.key}>
            <label className="block text-xs font-medium text-[var(--neutral-500)] uppercase tracking-wider mb-1.5">
              {field.label}
            </label>
            {field.type === "textarea" ? (
              <textarea
                className={textareaStyle + " !min-h-[80px]"}
                value={getFieldValue(field.key)}
                onChange={(e) => updateField(field.key, e.target.value)}
                placeholder={field.placeholder}
                data-field={field.key}
              />
            ) : (
              <input
                type="text"
                className={inputStyle}
                value={getFieldValue(field.key)}
                onChange={(e) => updateField(field.key, e.target.value)}
                placeholder={field.placeholder}
                data-field={field.key}
                onKeyDown={(e) => {
                  if (e.key === "Enter") {
                    e.preventDefault();
                    const idx = fields.findIndex((f) => f.key === field.key);
                    if (idx < fields.length - 1) {
                      const next = document.querySelector(
                        `[data-field="${fields[idx + 1].key}"]`
                      ) as HTMLElement | null;
                      next?.focus();
                    } else {
                      handleNext();
                    }
                  }
                }}
              />
            )}
          </div>
        ))}
      </div>
    );
  }

  function renderReviewStep() {
    const sections: { label: string; value: string; stepIndex: number }[] = [
      { label: "Brand Description", value: form.brandDescription, stepIndex: 0 },
      { label: "Campaign Description", value: form.campaignDescription, stepIndex: 1 },
      { label: "Deliverables", value: form.deliverables, stepIndex: 2 },
      { label: "Other Requirements", value: form.otherRequirements, stepIndex: 3 },
      { label: "Terms", value: form.terms, stepIndex: 4 },
      {
        label: "Products",
        value:
          form.selectedProductIds.size > 0
            ? `${form.selectedProductIds.size} product${form.selectedProductIds.size !== 1 ? "s" : ""} selected${form.productConditions ? ` \u2014 ${form.productConditions}` : ""}`
            : "No products selected",
        stepIndex: 5,
      },
      { label: "Gifting Instructions", value: form.giftingInstructions, stepIndex: 6 },
      {
        label: "Ideal Creator",
        value:
          [
            form.creatorNiche && `Niche: ${form.creatorNiche}`,
            form.creatorFollowerRange && `Followers: ${form.creatorFollowerRange}`,
            form.creatorGeography && `Geography: ${form.creatorGeography}`,
            form.creatorPlatforms && `Platforms: ${form.creatorPlatforms}`,
          ]
            .filter(Boolean)
            .join(" \u00B7 ") || "Not specified",
        stepIndex: 7,
      },
    ];

    return (
      <div className="space-y-3 max-h-[56vh] overflow-y-auto pr-1">
        {sections.map((s) => (
          <div
            key={s.label}
            className="rounded-xl border border-[var(--neutral-150)] bg-white p-4 flex items-start justify-between gap-3"
          >
            <div className="flex-1 min-w-0">
              <h4 className="text-xs font-semibold text-[var(--neutral-500)] uppercase tracking-wider mb-1">
                {s.label}
              </h4>
              <p className="text-sm text-[var(--neutral-700)] line-clamp-2 whitespace-pre-line">
                {s.value || (
                  <span className="italic text-[var(--neutral-300)]">Empty</span>
                )}
              </p>
            </div>
            <button
              type="button"
              onClick={() => goToStep(s.stepIndex)}
              className="shrink-0 flex items-center gap-1 text-xs font-medium text-[var(--brand-700)] hover:text-[var(--brand-800)] transition-colors mt-0.5"
            >
              <Pencil className="size-3" />
              Edit
            </button>
          </div>
        ))}

        <div className="pt-4 flex justify-center">
          <Button
            onClick={() => navigate("/campaigns")}
            className="px-8 h-11 text-sm font-semibold rounded-xl"
            style={{ backgroundColor: "var(--brand-700)", color: "white" }}
          >
            Launch Campaign
            <ArrowRight className="size-4 ml-2" />
          </Button>
        </div>
      </div>
    );
  }

  // ── Render switch ───────────────────────────────────────────────────────

  function renderStep() {
    switch (currentStep.type) {
      case "textarea":
        return renderTextareaStep();
      case "products":
        return renderProductsStep();
      case "creators":
        return renderCreatorsStep();
      case "review":
        return renderReviewStep();
      default:
        return null;
    }
  }

  // ── Main layout ─────────────────────────────────────────────────────────

  return (
    <div className="flex min-h-[calc(100vh-64px)] flex-col bg-[var(--neutral-25)]">
      {/* Progress bar — single, clean */}
      <div className="h-1 bg-[var(--neutral-100)]">
        <div
          style={{ width: `${((step + 1) / STEPS.length) * 100}%` }}
          className="h-full bg-[var(--brand-700)] transition-all duration-500 ease-out"
        />
      </div>

      {/* Split layout */}
      <div className="flex-1 flex flex-col items-center justify-center px-16 py-8">
        <div
          className="w-full rounded-2xl bg-white flex flex-col overflow-hidden"
          style={{ boxShadow: "0 4px 24px rgba(0,0,0,0.08), 0 1px 4px rgba(0,0,0,0.04)", minHeight: 480, maxWidth: 960 }}
        >
          <div className="flex flex-1 min-h-0">
          {/* ─── Left side: context & guidance ─── */}
          <div
            className="w-[360px] shrink-0 px-10 py-10 flex flex-col justify-between"
            style={{ backgroundColor: "#FAFAFA" }}
          >
            <div>
              {/* Step indicator — 11px, light weight, metadata feel */}
              <span
                className="text-[11px] font-medium uppercase tracking-widest"
                style={{ color: "var(--brand-400)" }}
              >
                Step {step + 1} of {STEPS.length}
              </span>

              {/* Title — 20px, anchors the section */}
              <div className="flex items-center gap-2.5 mt-5">
                <div
                  className="w-8 h-8 rounded-lg flex items-center justify-center shrink-0"
                  style={{ backgroundColor: "var(--brand-50)" }}
                >
                  <StepIcon className="size-4" style={{ color: "var(--brand-700)" }} />
                </div>
                <h1 className="text-[20px] font-bold text-[var(--neutral-900)] leading-tight">
                  {currentStep.title}
                </h1>
              </div>
              {/* Description — 14px */}
              <p className="text-[14px] text-[var(--neutral-500)]" style={{ lineHeight: 1.5 }}>
                {currentStep.subtitle}
              </p>

              {/* Good examples */}
              {currentStep.examples && currentStep.examples.length > 0 && (
                <div className="mt-6 px-4 py-3.5 rounded-xl bg-white border border-[var(--neutral-100)]">
                  <div className="flex items-center gap-1.5 mb-3">
                    <span className="text-base leading-none">💡</span>
                    <span className="text-[12px] font-bold uppercase tracking-widest" style={{ color: "var(--brand-600)" }}>
                      {currentStep.examplesLabel || "Good Examples"}
                    </span>
                  </div>
                  <div className="space-y-2.5">
                    {currentStep.examples.map((ex, i) => (
                      <p key={i} className="text-[13px] text-[var(--neutral-600)] leading-snug pl-1">
                        {currentStep.examplesLabel ? ex : `\u201C${ex}\u201D`}
                      </p>
                    ))}
                  </div>
                </div>
              )}
            </div>

            {/* Step dots — pinned to bottom */}
            <div className="flex items-center gap-1.5 mt-8">
              {STEPS.map((_, i) => (
                <button
                  key={i}
                  type="button"
                  onClick={() => goToStep(i)}
                  className="transition-all duration-300 rounded-full"
                  style={{
                    width: i === step ? 20 : 6,
                    height: 6,
                    backgroundColor:
                      i === step
                        ? "var(--brand-700)"
                        : i < step
                        ? "var(--brand-300)"
                        : "var(--neutral-200)",
                  }}
                />
              ))}
            </div>
          </div>

          {/* ─── Right side: form content ─── */}
          <div className="flex-1 min-w-0 px-10 pb-10 flex flex-col justify-start overflow-y-auto" style={{ paddingTop: "calc(2.5rem + 16px + 28px)" }}>
            <div className="w-full">
              <AnimatePresence mode="wait" custom={direction}>
                <motion.div
                  key={step}
                  custom={direction}
                  variants={variants}
                  initial="enter"
                  animate="center"
                  exit="exit"
                  transition={transition}
                >
                  {renderStep()}
                </motion.div>
              </AnimatePresence>
            </div>
          </div>

          </div>
        </div>

        {/* Floating buttons — under the card, aligned with sides */}
        <div className="flex justify-between mt-5" style={{ width: "100%", maxWidth: 960 }}>
          <Button
            variant="outline"
            onClick={handleBack}
            disabled={step === 0}
            className="h-10 px-5 rounded-xl text-sm bg-white disabled:opacity-0"
            style={{ boxShadow: "0 2px 12px rgba(0,0,0,0.06)" }}
          >
            <ArrowLeft className="size-4 mr-1.5" />
            Back
          </Button>

          <Button
            onClick={handleNext}
            className="h-10 px-6 rounded-xl text-sm font-semibold"
            style={{ backgroundColor: "var(--brand-700)", color: "white", boxShadow: "0 2px 12px rgba(0,0,0,0.1)" }}
          >
            {step === STEPS.length - 1 ? "Launch Campaign" : "Continue"}
            <ArrowRight className="size-4 ml-1.5" />
          </Button>
        </div>
      </div>
    </div>
  );
}
